apiVersion: v1
kind: ConfigMap
metadata:
  name: torchserve-config
  namespace: torchserve
data:
  config.properties: |
    inference_address=http://0.0.0.0:8080
    management_address=http://0.0.0.0:8081
    metrics_address=http://0.0.0.0:8082
    number_of_netty_threads=4
    job_queue_size=100
    model_store=/mnt/models
    load_models=model.mar
    default_workers_per_model=1